Firstname = input("Enter First Name: ")
Lastname = input("Enter Last Name: ")
Middlename = input("Enter Middle Name: ")
Birthday = input("Enter Birthday: ")
Gender = input("Enter Gender: ")
Address = input("Enter Address: ")
Course = input("Enter Course: ")
Yearlevel = input("Enter Year Level: ")

print("\n\nFirst Name: ",Firstname)
print("Last Name: ",Lastname)
print("Middle Name: ",Middlename)
print("Birthday: ",Birthday)
print("Gender: ",Gender)
print("Address: ",Address)
print("Course: ",Course)
print("Year Level: ",Yearlevel)